name: Ranked development
description: A rating system of contributors
author: Victor Semenov
inputs:
  devrating-organization:
    description: Your Organization_ID. Visit https://devrating.net/#/keys to obtain
    required: true
  devrating-api-key:
    description: Your API_Key. Visit https://devrating.net/#/keys to create new
    required: true
  devrating-repository:
    description: The repository name to be shown on devrating.net
    default: ${{ github.repository }}
    required: false
  base-branch:
    description: Your main development branch (usually 'master' or 'main')
    default: ${{ github.base_ref || github.event.repository.default_branch }}
    required: false
  max-additions:
    description: Skips PRs with more added lines of code. "0" — no limits
    default: "4000"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/script.sh \
        '${{ inputs.devrating-repository }}' \
        '${{ inputs.devrating-organization }}' \
        '${{ inputs.devrating-api-key }}' \
        '${{ inputs.base-branch }}' \
        '${{ github.token }}' \
        '${{ inputs.max-additions }}'
      shell: sh

branding:
  icon: thumbs-up
  color: yellow
